# system modes safety benchmark
---

safety:
  ros__parameters:
    type: system
    parts:
      image_1_to_2
      imu_1_to_2
      odom_1_to_2
      pc2_1_to_2
      scan_1_to_2
      tf_1_to_2
      tf_static_1_to_2
      twist_2_to_1
    modes:
      __DEFAULT__:
        image_1_to_2: active
        imu_1_to_2: active
        odom_1_to_2: active
        pc2_1_to_2: active
        scan_1_to_2: active
        tf_1_to_2: active
        tf_static_1_to_2: active
        twist_2_to_1: active
      ALERT:
        image_1_to_2: inactive
        imu_1_to_2: active
        odom_1_to_2: active
        pc2_1_to_2: active
        scan_1_to_2: active
        tf_1_to_2: active
        tf_static_1_to_2: active
        twist_2_to_1: active
      COMPROMISED:
        image_1_to_2: inactive
        imu_1_to_2: active
        odom_1_to_2: active
        pc2_1_to_2: inactive
        scan_1_to_2: inactive
        tf_1_to_2: active
        tf_static_1_to_2: active
        twist_2_to_1: inactive
      HALT:
        image_1_to_2: inactive
        imu_1_to_2: inactive
        odom_1_to_2: inactive
        pc2_1_to_2: inactive
        scan_1_to_2: inactive
        tf_1_to_2: inactive
        tf_static_1_to_2: inactive
        twist_2_to_1: inactive

image_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

imu_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

odom_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

pc2_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

scan_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

tf_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

tf_static_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      

twist_2_to_1:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      SOFT:
        ros__parameters:
          use_sim_time: false
      